apiVersion: v1
kind: Service
metadata:
  name: nginx-hello-service
spec:
  type: NodePort
  selector:
    app: nginx-hello
  ports:
  - port: 80
    targetPort: 80  # container port
    nodePort: 30080 #this is node port

